# [Problem 1] Enumeration of classes used so far

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [2]:
data = load_iris()
X = data.data[:10]

In [3]:
scaler = StandardScaler()
scaler.fit(X)
print("average :", scaler.mean_)
print("dispersion :", scaler.var_)
X_std = scaler.transform(X)


average : [4.86 3.31 1.45 0.22]
dispersion : [0.0764 0.0849 0.0105 0.0056]


In [4]:
scaler0 = StandardScaler()
print(scaler0)
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler()


StandardScaler()

**Pandas**<br>
- DataFrame()
- Series()
- Index()
- Categorical()

**matplotlib**<br>
- RcParams()
- Parameter()
- Path()

**scikit-learn**
- LinearRegression()
- DecisionTreeClassifier()
- StandardScaler()

### [Problem 2] Enumeration of methods and instance variables used so far

**methods**
- df.drop()
- df.mean()
- plt.xlabel()
- np.delete()
- plt.show()

**variables**
- np.T
- np.data
- np.shap
- np.ndim
- np.size

# [Problem 3] Creating a standardized class by scratch

In [5]:
class ScratchStandardScaler():
    def fit(self, X):
        self.mean = np.mean(X, axis=0)
        self.var = np.var(X, axis=0)
            
    def transform(self, X):
        X_mean = X.mean(axis=0)
        X_std  = X.std(axis=0)
        X_scaled = (X - X_mean) / X_std
        return X_scaled
    
         

In [6]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)

print("mean : {}".format(scratch_scaler.mean))
print("distributed : {}".format(scratch_scaler.var))

X_std = scratch_scaler.transform(X)
print(X_std)


mean : [4.86 3.31 1.45 0.22]
distributed : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# [Problem 4] Creating a class that performs 4 arithmetic operations

In [7]:
class ArthCalc():
    def __init__(self, value):
        if not isinstance(value, (int, float)):
            print("Enter numbers Only")
        else:
            self.value = value
            print("The initial value {} has been set".format(self.value))
    def add(self, value2):
        self.value += value2

    def subtraction(self, value):
        self.value -= value
        
    def multiplication(self, value):
        self.value *= value
        
    def division(self, value):
        self.value /= value
example = ArthCalc(10)
print("value : {}".format(example.value))
example.add(4)
print(" addition value : {}".format(example.value))

example.subtraction(5)
print("subtraction value : {}".format(example.value))

example.multiplication(5)
print("multiplication value : {}".format(example.value))

example.division(3)
print("division value : {}".format(example.value))    



The initial value 10 has been set
value : 10
 addition value : 14
subtraction value : 9
multiplication value : 45
division value : 15.0
